### ISSUE TITLE
PXF - Selecting non-existent parquet files or parquet files with an incomplete schema

### ISSUE THREAD

**Issue by artem-zav** [greenplum-db/pxf#1083]
Hi, is there a setting/config option to make pxf work without throwing following errors?

we have created multiple external increment tables, but we do not always have any data files in them, we would like to see that there are 0 rows, but instead we get this error:

select * from public.notification;
```
SQL Error [08000]: ERROR: PXF server error : Input path does not exist: s3a://datalake/ods/increment_data/notification.parquet  (seg0 slice1 10.128.0.6:6000 pid=16338)
  Hint: Check the PXF logs located in the '/usr/local/pxf-gp6/logs' directory on host 'localhost' or 'set client_min_messages=LOG' for additional details.
  Where: External table notification
```
  
we have added a new column (test_field) to our external table, but we already have data files without this column in this table location,  we would like to see all our data and nulls in this new column, but instead we get this error:

select * from public.notification1_test;
```
  SQL Error [08000]: ERROR: PXF server error : Column test_field is missing from parquet schema  (seg4 slice1 10.128.0.6:6004 pid=16966)
  Hint: Check the PXF logs located in the '/usr/local/pxf-gp6/logs' directory on host 'localhost' or 'set client_min_messages=LOG' for additional details.
  Where: External table notification1_test
```
  
  
  
We use this setting currently:

myminio-site.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <property>
        <name>fs.s3a.endpoint</name>
        <value>http://s3-myminio:9000</value>
    </property>
    <property>
        <name>fs.s3a.access.key</name>
        <value>123</value>
    </property>
    <property>
        <name>fs.s3a.secret.key</name>
        <value>12345</value>
    </property>
    <property>
        <name>fs.s3a.fast.upload</name>
        <value>true</value>
    </property>
    <property>
        <name>fs.s3a.path.style.access</name>
        <value>true</value>
    </property>
</configuration>
```

creating table example
```
CREATE EXTERNAL TABLE ods.notification1_test(
	content text,
	test_field text
)
LOCATION (
	'pxf://datalake/ods/increment_data/notification1.parquet?PROFILE=s3:parquet&SERVER=myminio'
) ON ALL
FORMAT 'CUSTOM' ( FORMATTER='pxfwritable_import' )
ENCODING 'UTF8';
```

Thanks!

**Comment by denalex** [comment]
Hi @artem-zav, to answer your questions:

1. To work around a situation where the files do not yet exist you have 2 options:
    a) use a directory path, not the actual file: `LOCATION ('pxf://datalake/ods/increment_data?PROFILE...`
    b) use `IGNORE_MISSING_PATH=true` option in the location URL. This option will ignore incorrect/non-existing paths, so there is less protection against accidentally mistyping the path as such mistakes will not be detected and no records will be returned.

2. Unfortunately, at the moment, the schema evolution for Parquet is not supported and if the Greenplum schema has an extra field that a Parquet file does not, we check and throw an error: https://github.com/greenplum-db/pxf/blob/main/server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/ParquetFileAccessor.java#L408 So this would be a new feature to ignore such columns and backfill them with NULL.

**Comment by artem-zav** [comment]
Hi @denalex , thank you for your response, 1)IGNORE_MISSING_PATH=true really helped. as for 2) it looks like we'll have to solve this problem by rewriting our parquets and maybe wait until scheme evolution is implemented in pxf(if that ever happens).
Thank you again
