### ISSUE TITLE
Add isolation level to JDBC Server configuration file

### ISSUE THREAD

**Issue by pivotalguru** [greenplum-db/pxf#130]
Databases like DB2 and SQL Server use locking to provide read consistency so long running queries can block other sessions from updating a table.  To prevent this, many users of these databases will use dirty reads to prevent blocking locks.  This is achieved in JDBC by setting the transaction isolation level to read uncommitted.  

Example:
```
int transactionIsolationLevel = 0;

if (readCommitted) 
  transactionIsolationLevel = Connection.TRANSACTION_READ_COMMITTED;
else
  transactionIsolationLevel = Connection.TRANSACTION_READ_UNCOMMITTED;

conn.setTransactionIsolation(transactionIsolationLevel);
```
So add property to JDBC server configuration file so that the read isolation level can be set.  The default should be read committed.

**Comment by frankgh** [comment]
This will be released in PXF version 5.3.0
