### ISSUE TITLE
ERROR:  invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by clxy** [greenplum-db/pxf#139]
Version: 5.1.6

We got an error when accessing a text file on S3.

> ERROR:  invalid byte sequence for encoding "UTF8": 0x81  (seg1 slice1 1.2.3.4:6001 pid=3023)
DETAIL:  External table my_table, line 1 of pxf://my_bucket/my_file?PROFILE=s3:text&SERVER=s3ssp&COMPRESSION_TYPE=BLOCK: "2019-04-02 20:43:29	0000	0000	0000	https://url	domain.com			https://url	https://url?param1=z:\MS_Att..."
SQL state: 22021

And we tracked down the data row(tab separated),

>2019-04-02 20:43:29	0000	0000	0000	https://url	domain.com			https://url	https://url?param1=z:\MS_AttachZ2\Picture\R2583000\2583419\2\2019-04-02_11.45.42.jpg&param2=https://url	594	0			Edge 42.17134.1.0	674904952								2019-04-02

It seems that those backslashes caused the error. 

External table
```sql
CREATE EXTERNAL TABLE public.my_table(
    col1 text,
    col2 text,
    col3 text,
    col4 text,
    col5 text,
    col6 text,
    col7 text,
    col8 text,
    col9 text,
    col10 text,
    col11 integer,
    col12 text,
    col13 text,
    col14 text,
    col15 text,
    col16 text,
    col17 text,
    col18 text,
    col19 text,
    col20 text,
    col21 text,
    col22 text,
    col23 text,
    col24 text)
LOCATION (
    'pxf://my_bucket/my_file?PROFILE=s3:text&SERVER=s3ssp&COMPRESSION_TYPE=BLOCK')
ON ALL
FORMAT 'text' (delimiter E'\t')
ENCODING 'UTF8'
;
```

Thanks

**Comment by frankgh** [comment]
@clxy Can you try disabling escaping?
```sql
CREATE EXTERNAL TABLE public.my_table(
    col1 text,
    col2 text,
    col3 text,
    col4 text,
    col5 text,
    col6 text,
    col7 text,
    col8 text,
    col9 text,
    col10 text,
    col11 integer,
    col12 text,
    col13 text,
    col14 text,
    col15 text,
    col16 text,
    col17 text,
    col18 text,
    col19 text,
    col20 text,
    col21 text,
    col22 text,
    col23 text,
    col24 text)
LOCATION (
    'pxf://my_bucket/my_file?PROFILE=s3:text&SERVER=s3ssp&COMPRESSION_TYPE=BLOCK')
ON ALL
FORMAT 'text' (delimiter E'\t' ESCAPE 'OFF')
ENCODING 'UTF8'
;
```

**Comment by clxy** [comment]
@frankgh 

Problem solved!

Sorry for so newbie question,
And Thank you for answering.

**Comment by frankgh** [comment]
@clxy I'm glad my suggestion worked out. Feel free to reach out even for small questions!
