### ISSUE TITLE
pxfwritable_export - ERROR:  failed sending to remote component

### ISSUE THREAD

**Issue by sree80** [greenplum-db/pxf#184]
Here is the steps on what I did.

1) Create a new database pgtest
template1=# CREATE DATABASE pgtest;
CREATE DATABASE
template1=# \c pgtest

2) connect to pgtest database and create a new table and insert one row.
pgtest=# CREATE TABLE public.test (id integer);
CREATE TABLE
pgtest=# INSERT INTO public.test values (1);
INSERT 0 1

3) connect to template1 database
pgtest=# \c template1
template1=# CREATE WRITABLE EXTERNAL TABLE pxf_writeto_postgres(id int)
template1-# LOCATION ( 'pxf://public.test?PROFILE=JDBC&JDBC_DRIVER=org.postgresql.Driver&DB_URL=jdbc:postgresql://localhost:15432/pgtest&USER=gpadmin') FORMAT 'CUSTOM' (FORMATTER='pxfwritable_export');

CREATE EXTERNAL TABLE
template1=# INSERT INTO pxf_writeto_postgres VALUES (111);

ERROR:  failed sending to remote component '127.0.0.1:5888' (libchurl.c:620)  (seg1 172.17.0.2:50001 pid=9738) (libchurl.c:620)

I'm on
PostgreSQL 9.4.20
Greenplum Database 6.0.0-beta.3
PXF version 5.3.2

**Comment by frankgh** [comment]
@sree80 we believe this is related to the postgres driver (42.2.5) that we are using. Can you install the latest postgres driver in `$PXF_CONF/lib`? After that you will need to run a `pxf cluster sync` (on multinode setup) and `pxf cluster restart`.

**Comment by frankgh** [comment]
Please see related PR: https://github.com/greenplum-db/pxf/pull/183

**Comment by frankgh** [comment]
@sree80 closing for now since we have a fix for it. Let me know if you still run into issues with the new driver.
