### ISSUE TITLE
GreenPlum 5.11 PXF Issue

### ISSUE THREAD

**Issue by sree80** [greenplum-db/pxf#185]
https://gpdb.docs.pivotal.io/5110/pxf/client_instcfg.html

I followed the instruction set in this page, but some of the instructions are very unclear.

I used the Cloudera distributions for hadoop and pretty much followed the instruction documented in this page.

but when I  initialize PXF, it throws me the below error
ERROR: Can not determine Hadoop distribution, please install Hadoop clients.

Not sure what is wrong here.

**Comment by frankgh** [comment]
Please refer to this page: https://gpdb.docs.pivotal.io/5110/pxf/client_instcfg.html
Under the `Using a Custom Client Installation` section. Let us know if that helps

**Comment by frankgh** [comment]
Closing this for now.
