### ISSUE TITLE
PXF JDBC select ERROR while the column name it happens to be a keywords

### ISSUE THREAD

**Issue by whirlys** [greenplum-db/pxf#200]
I want to load some data from mysql to greenplum using PXF, and I did these:

in mysql:
```sql
CREATE TABLE `test` (
	`id` BIGINT(20) UNSIGNED NOT NULL,
	`name` VARCHAR(54) NOT NULL,
	`group` INT(10) UNSIGNED NOT NULL,
	`user` VARCHAR(254) NOT NULL
);
INSERT INTO test VALUES (1, "whirly", 11, "hello");
```

in greenplum:
```
CREATE READABLE EXTERNAL TABLE pxf_test (
	id BIGINT,
	name VARCHAR(54),
	"group" INTEGER,
	"user" VARCHAR(254) 
)LOCATION ('pxf://test?PROFILE=Jdbc&SERVER=aclog')
FORMAT 'CUSTOM' (FORMATTER='pxfwritable_import');
```

and query data in psql:
```sql
select * from pxf_test;
```

then get ERROR:
```
ERROR:  remote component error (500) from '127.0.0.1:5888':  type  Exception report   message   
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server 
version for the right syntax to use near 'group, user FROM test' at line 1    description   The 
server encountered an internal error that prevented it from fulfilling this request.    exception   
java.io.IOException: You have an error in your SQL syntax; check the manual that corresponds to 
your MySQL server version for the right syntax to use near 'group, user FROM test' at line 1 
(libchurl.c:944)  (seg0 slice1 28.28.15.202:7000 pid=3017) (cdbdisp.c:254)
DETAIL:  External table pxf_test
```

I guess that it was cause by the column "group" and "user", They happen to be the keywords of MySQL.

I used '', "", "``", but it does not take effect.

env:
- PXF version: 5.6.0
- Greenplum version: 5.18
- MySQL connector: mysql-connector-java-5.1.47-bin.jar
- MySQL version: mysql-5.7.26-winx64

**Comment by frankgh** [comment]
@whirlys you can force quotes on the external system, by adding `&QUOTE_COLUMNS=true', for this special cases as specified in the [documentation](https://gpdb.docs.pivotal.io/5200/pxf/jdbc_pxf.html):
```sql
CREATE READABLE EXTERNAL TABLE pxf_test (
	id BIGINT,
	name VARCHAR(54),
	"group" INTEGER,
	"user" VARCHAR(254) 
)LOCATION ('pxf://test?PROFILE=Jdbc&SERVER=aclog&QUOTE_COLUMNS=true')
FORMAT 'CUSTOM' (FORMATTER='pxfwritable_import');
```

Please let me know if this helps

**Comment by frankgh** [comment]
I just realized that the `QUOTE_COLUMNS` feature is supported starting in Greenplum version: 5.19, but if you are running on PXF version 5.6.0 `QUOTE_COLUMNS` should be available for you.

**Comment by whirlys** [comment]
@frankgh Thank you very much, it worked, solved my problem.

**Comment by frankgh** [comment]
great! closing this issue then. Thank you
