### ISSUE TITLE
PXF can't running on gpdb6.0.beta7

### ISSUE THREAD

**Issue by pengzhanyuan** [greenplum-db/pxf#223]
when i use command "pxf cluster start" to startup the pxf service,the tomcat is up and the PXF is down.The error likes this:
1. java.lang.NoSuchMethodException: org.apache.catalina.deploy.WebXml setSessionConfig
2. java.lang.NoSuchMethodException: org.apache.catalina.deploy.WebXml addServlet
more detail error on ​attached file.
​
Environment:
OS: CentOS 6.10
Kernel:​3.18.140-11.el6.x86_64
DB server: GPDB 6.0.beta7
pxf version:PXF version 5.7.0
Tomcat: Apache Tomcat/7.0.62​
JVM Version:1.8.0_91-b14

**Comment by pengzhanyuan** [comment]
[catalina.txt](https://github.com/greenplum-db/pxf/files/3532705/catalina.txt)

**Comment by frankgh** [comment]
@pengzhanyuan can you verify you have the following:
`$PXF_HOME/apache-tomcat`
`$PXF_HOME/pxf-service/lib/catalina.jar`

Can you also share your `$PXF_HOME/pxf-service/webapps/pxf/WEB-INF/web.xml` file?
Thank you,

**Comment by pengzhanyuan** [comment]
[web.xml.txt](https://github.com/greenplum-db/pxf/files/3533628/web.xml.txt)
This is my $PXF_HOME/pxf-service/webapps/pxf/WEB-INF/web.xml file

**Comment by pengzhanyuan** [comment]
[operating:install_pxf.md.txt](https://github.com/greenplum-db/pxf/files/3534589/operating.install_pxf.md.txt)

These are all my operating of  pxf serveice initialization

**Comment by pengzhanyuan** [comment]
`
$ ll $PXF_HOME/apache-tomcat
total 116
drwxr-xr-x 2 gpadmin gpadmin  4096 Aug 21 15:28 bin
drwxr-xr-x 2 gpadmin gpadmin  4096 Aug 21 15:28 conf
drwxr-xr-x 2 gpadmin gpadmin  4096 Aug 21 15:28 lib
-rw-r--r-- 1 gpadmin gpadmin 56812 Aug 15 02:32 LICENSE
drwxr-xr-x 2 gpadmin gpadmin  4096 Aug 15 02:32 logs
-rw-r--r-- 1 gpadmin gpadmin  1192 Aug 15 02:32 NOTICE
-rw-r--r-- 1 gpadmin gpadmin  8965 Aug 15 02:32 RELEASE-NOTES
-rw-r--r-- 1 gpadmin gpadmin 16204 Aug 15 02:32 RUNNING.txt
drwxr-xr-x 2 gpadmin gpadmin  4096 Aug 21 15:28 temp
drwxr-xr-x 7 gpadmin gpadmin  4096 Aug 21 15:28 webapps
drwxr-xr-x 2 gpadmin gpadmin  4096 Aug 15 02:32 work

$ ll $PXF_HOME/pxf-service/lib/catalina.jar
-rw-r--r-- 1 gpadmin gpadmin 1621907 Aug 21 16:51 /usr/local/greenplum-db/pxf/pxf-service/lib/catalina.jar

$ cd $PXF_HOME/pxf-service/lib/
$ ls |xargs -I{} jar -tf {} | grep -ri "setSessionConfig"
Binary file catalina.jar matches
$ ls |xargs -I{} jar -tf {} | grep -ri "addServlet"
`
In catalina.jar ,There's "setSessionConfig" method, but there's no "addServlet" method in any jar packet.

**Comment by frankgh** [comment]
@pengzhanyuan I wanted to make sure you were able to fix the issue? We tried reproducing internally, but were unable to reproduce.
