### ISSUE TITLE
PXF read Hive transactional table Error

### ISSUE THREAD

**Issue by whirlys** [greenplum-db/pxf#240]
When I set a Hive ORC table to `TBLPROPERTIES ('transactional'='true')`，it will report an exception.

### environment
- greenplum: 5.21
- Hive: HDP 3.1

### step
note: the sample data is the data on the official document, http://docs.greenplum.org/5190/pxf/hive_pxf.html#hive_orc

- step1: create HIVE ORC table (transactional)
```
CREATE TABLE sales_info_ORC 
	(location string, month string, number_of_orders int, total_sales double) 
clustered by (number_of_orders) into 8 buckets 
STORED AS ORC 
TBLPROPERTIES ('transactional'='true');
```

- step2: load data from sales_info to sales_info_ORC 
```
INSERT INTO TABLE sales_info_ORC SELECT * FROM sales_info;
```

- step3: create PXF EXTERNAL TABLE 
```
CREATE EXTERNAL TABLE salesinfo_hiveORCprofile
	(location text, month text, number_of_orders int, total_sales float8)
LOCATION ('pxf://zh.sales_info_ORC?PROFILE=HiveORC&SERVER=hivetest')
FORMAT 'CUSTOM' (FORMATTER='pxfwritable_import');
```

- step 4: read the PXF table and it will report exception
```
default=# select * from salesinfo_hiveORCprofile;
ERROR:  remote component error (500) from '127.0.0.1:5888':  type  Exception report   
message   serious problem    description   The server encountered an internal error 
that prevented it from fulfilling this request.    exception   
java.lang.RuntimeException: serious problem (libchurl.c:946)  (seg0 slice1 192.168.192.1:6000 
pid=10889) (cdbdisp.c:254)
DETAIL:  External table salesinfo_hiveorcprofile
```

**Comment by denalex** [comment]
PXF does NOT yet support Hive3, which is included in HDP3. I wonder, though, does it work when you do not specify `TBLPROPERTIES ('transactional'='true')` in the Hive table definition ?

**Comment by whirlys** [comment]
@denalex Yes, it work in other case. Thanks
