### ISSUE TITLE
Querying external database thru JDBC without presave

### ISSUE THREAD

**Issue by anki-code** [greenplum-db/pxf#245]
Hi! Thank you for PXF! It helps!

According [Greenplum JDBC PXF manual](https://gpdb.docs.pivotal.io/6-0/pxf/jdbc_pxf.html) there is ability to create presaved queries and call it via `pxf://query:<query_name>`.

But I need to use the external database with different types of queries. In short I need change query to the external database every time. And I can't use pushdown SQL syntax for it (like `select columns from external_tbl where ...`) because the database has not SQL syntax. Everything I can it's make `select * from ext_table` and set the external query to the definition of `ext_table`.

@frankgh @denalex Could you please advice the best way for it? Probably there is a magic to pass the query to PXF thru external table connection string?

Thanks!

**Comment by denalex** [comment]
@anki-code -- PXF is not currently designed to allow custom SQL queries to be sent via JDBC connector, mostly due to security pre-cautions. 

But PXF has some flexibility to set session level parameters as well as parameters specific to each user. Maybe you can describe in more details why you want custom SQL and we can see if the problem can be solved with the current functionality.

**Comment by anki-code** [comment]
@denalex  I need to querying the data from the neo4j graph database in gpdb. Neo4j has query language called Cypher a bit similar as SQL and can return the data as rows and columns.

The best for me (and I think for everyone who want to querying external databases) is the ability to send any query to jdbc connector and get the result. 

It allows to create usecases like `SELECT db_neo('<query to neo4j db>');` where `db_neo` is the function which create external table with PXF and select from it.

**Comment by anki-code** [comment]
The month passed since I answered. Could you please tell about your thoughts. Is this feature could appear or it's out of pxf concepts? May be any technical problems exist? From my point PXF in Greenplum is the door to the outside world and JDBC is the common simplest way to go thru. If it's wrong please tell me.

**Comment by frankgh** [comment]
@anki-code this feature is in our radar, but we don't have a definite timeline to implement it. We'll update this thread once we have the feature ready.
