### ISSUE TITLE
is support hadoop3 erasure coding policies

### ISSUE THREAD

**Issue by wynn3** [greenplum-db/pxf#275]
my hadoop cluster version is 3.1.0 ,when a path not open erasure coding policies ,the EXTERNAL table read normal ,when open the erasure coding policies read failed. so pxf not support this or need configure.

**Comment by frankgh** [comment]
@wynn3 which policy are you using?

**Comment by frankgh** [comment]
We don't have enough information to keep investigating. Closing the issue for now. Please feel free to reopen it with additional information
