### ISSUE TITLE
Some tests failed while building

### ISSUE THREAD

**Issue by m7onov** [greenplum-db/pxf#303]
There are 2 tests that fail: [failed-tests.zip](https://github.com/greenplum-db/pxf/files/4203336/failed-tests.zip)

**Comment by frankgh** [comment]
hi @m7onov , can you provide your JDK information. Are you building master?

**Comment by frankgh** [comment]
@m7onov is this still an issue?

**Comment by m7onov** [comment]
Hello. Sorry for dealy
```
java -version

openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10-LTS, mixed mode, sharing)
```

**Comment by frankgh** [comment]
Currently Java 11 is not supported for tests. This is from our README:
> To build PXF, you must have:
> 
> JDK 1.8 to compile (PXF runs on Java 8 and Java 11)
> Go (1.9 or later)
> unzip

**Comment by m7onov** [comment]
I missed that in the README, sorry. Thanks for the clarification
