### ISSUE TITLE
ESCAPE 'OFF' is not processed correctly on PXF side

### ISSUE THREAD

**Issue by kapustor** [greenplum-db/pxf#307]
GP 6.4, PXF 5.10.1.
We can create a valid external table with ESCAPE 'OFF' clause:
```
CREATE EXTERNAL TABLE test (test text)
LOCATION ('pxf://folder?PROFILE=hdfs:text')
FORMAT 'TEXT' ( ESCAPE 'OFF');
```
The table is created successfully, but while selecting we got the following error:
```
ERROR:  remote component error (500) from '127.0.0.1:5888':  Type  Exception Report   Message  invalid ESCAPE character 'OFF'. Only single character is allowed for ESCAPE.   Description  The server encountered an unexpected condition that prevented it from fulfilling the request.   Exception   java.lang.IllegalArgumentException: invalid ESCAPE character 'OFF'. Only single character is allowed for ESCAPE. (libchurl.c:920)  (seg0 slice1 10.92.8.11:10000 pid=23082) (libchurl.c:920)
CONTEXT:  External table test, line 1 of file pxf://folder?PROFILE=hdfs:text
```
It seems that PXF should process ESCAPE 'OFF' correctly and ignore all escape symbols.

**Comment by oliverralbertini** [comment]
Thanks for the report, @kapustor . Could you also add some example data that causes this error?

**Comment by kapustor** [comment]
Hi @oliverralbertini, the error occurs earlier than PXF gets any data, even without connected HDFS. Just deploy any GP cluster, install and run PXF and create external table.
