### ISSUE TITLE
Invalid DELIMITER character 

### ISSUE THREAD

**Issue by poas187** [greenplum-db/pxf#349]
Following instructions here to install PXF in docker: https://github.com/greenplum-db/pxf/blob/master/README.md
Docker image base:  pivotaldata/gpdb-pxf-dev:centos6
PXF version: 5.10.0

I use psql to run the following:
>template1=# \l
                       List of databases
        Name        |  Owner  | Encoding |  Access privileges
--------------------+---------+----------+---------------------
 contrib_regression | gpadmin | UTF8     |
 gpadmin            | gpadmin | UTF8     |
 postgres           | gpadmin | UTF8     |
 template0          | gpadmin | UTF8     | =c/gpadmin
                                         : gpadmin=CTc/gpadmin
 template1          | gpadmin | UTF8     | =c/gpadmin
                                         : gpadmin=CTc/gpadmin
(5 rows)
template1=# CREATE EXTERNAL TABLE my_table(a TEXT) LOCATION ('pxf://myfile?PROFILE=Hive') FORMAT 'TEXT';
CREATE EXTERNAL TABLE
template1=#
template1=# select * from my_table;
ERROR:  remote component error (500) from '127.0.0.1:5888':  Type  Exception Report   Message  invalid DELIMITER character '%09'. Only single character is allowed for DELIMITER.   Description  The server encountered an unexpected condition that prevented it from fulfilling the request.   Exception   java.lang.IllegalArgumentException: invalid DELIMITER character '%09'. Only single character is allowed for DELIMITER. (libchurl.c:963)  (seg0 slice1 172.26.0.3:25432 pid=11040) (cdbdisp.c:254)
DETAIL:  External table my_table, file pxf://myfile?PROFILE=Hive
template1=#
template1=# CREATE EXTERNAL TABLE my_table_s3(a TEXT) LOCATION ('pxf://myfile?PROFILE=s3:text') FORMAT 'TEXT';
CREATE EXTERNAL TABLE
template1=#
template1=# select * from my_table_s3;
ERROR:  remote component error (500) from '127.0.0.1:5888':  Type  Exception Report   Message  s3%3Atext is not defined in pxf-profiles.xml   Description  The server encountered an unexpected condition that prevented it from fulfilling the request.   Exception   org.greenplum.pxf.service.profile.ProfileConfException: s3%3Atext is not defined in pxf-profiles.xml (libchurl.c:963)  (seg0 slice1 172.26.0.3:25432 pid=11052) (cdbdisp.c:254)
DETAIL:  External table my_table_s3, file pxf://myfile?PROFILE=s3:text
template1=#

I tried setting a specific delimiter, but same behaviour.
In the two different errors, the cause seems to be the same: a problem with the characters.  E.g. pxf has a profile with name s3:text. but instead is trying to find a profile with name s3%3Atext, which does not find.

In case it is useful, here is some logs from pxf server:
>Apr 27, 2020 11:44:00 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
org.greenplum.pxf.service.profile.ProfileConfException: s3%3Atext is not defined in pxf-profiles.xml
        at org.greenplum.pxf.service.profile.ProfilesConf.getProfile(ProfilesConf.java:118)
        at org.greenplum.pxf.service.profile.ProfilesConf.getPlugins(ProfilesConf.java:97)
        at org.greenplum.pxf.service.HttpRequestParser.addProfilePlugins(HttpRequestParser.java:266)
        at org.greenplum.pxf.service.HttpRequestParser.parseRequest(HttpRequestParser.java:84)
        at org.greenplum.pxf.service.HttpRequestParser.parseRequest(HttpRequestParser.java:30)
        at org.greenplum.pxf.service.rest.BaseResource.parseRequest(BaseResource.java:40)
        at org.greenplum.pxf.service.rest.FragmenterResource.getFragments(FragmenterResource.java:110)

**Comment by frankgh** [comment]
@poas187 you are using a Greenplum version that is incompatible with PXF Version 5.10.0. To solve this issue, please upgrade your PXF to [version 5.11.2](https://github.com/greenplum-db/pxf/releases/tag/5.11.2). The specific incompatibility is due to PR #316.

**Comment by poas187** [comment]
I started over using this time version "5.11.2" for pxf, and "5x_STABLE" for gpdb and it worked.
Thanks for your help.

**Comment by frankgh** [comment]
great news @poas187 !
