### ISSUE TITLE
insert char into inner table from pxf

### ISSUE THREAD

**Issue by ryonchen** [greenplum-db/pxf#428]
I link to MySQL through PXF and write it to the GP internal table. There is a field of char type. For example:
`
inner tabel:
CREATE EXTERNAL TABLE inner_schema.tb( 
id                   bigint       ,
name char(5));

EXTERNAL  tabel:
CREATE EXTERNAL TABLE ext_schema.tb( 
id                   bigint       ,
name char(5))
LOCATION ('pxf://tb?PROFILE=Jdbc&SERVER=jdbc_mysql&QUOTE_COLUMNS=true')
            FORMAT 'CUSTOM' (FORMATTER='pxfwritable_import');

INSERT INTO schema.tb select * from ext_schema.tb;
 `
The name's value in MySQL is '1', I expect the same in GP.BUT it is '1     ' in GP.There are 4 spaces after 1.

**Comment by frankgh** [comment]
@ryonchen Greenplum will pad `char(n)` types to the number of `n` digits. I just tried this locally. PXF ships a single character to Greenplum, but Greenplum adds padding in the result set.

If you don't want the padding, use the `varchar` type instead on the Greenplum side, for example:

```
CREATE EXTERNAL TABLE ext_schema.tb(
id bigint ,
name varchar(5))
LOCATION ('pxf://tb?PROFILE=Jdbc&SERVER=jdbc_mysql&QUOTE_COLUMNS=true')
FORMAT 'CUSTOM' (FORMATTER='pxfwritable_import');
```

**Comment by frankgh** [comment]
@ryonchen is this still an issue? can we close it?

**Comment by frankgh** [comment]
closing for now. Hopefully the workaround provided works
