### ISSUE TITLE
unit test error when make install

### ISSUE THREAD

**Issue by liuyiffan** [greenplum-db/pxf#517]
$ java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (build 25.272-b10, mixed mode)

$ make -C ~/pxf install
\> Task :pxf-api:test

org.greenplum.pxf.api.security.SecureLoginTest > testPrincipalGetsResolvedForServer() FAILED
    org.opentest4j.AssertionFailedError at SecureLoginTest.java:389

org.greenplum.pxf.api.security.SecureLoginTest > testLoginKerberosReuseExistingLoginSessionWithResolvedHostnameInPrincipal() FAILED
    java.lang.RuntimeException at SecureLoginTest.java:346
        Caused by: java.lang.NullPointerException at SecureLoginTest.java:346

339 tests completed, 2 failed

\> Task :pxf-api:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pxf-api:test'.
\> There were failing tests. See the report at: file:///home/gpadmin/pxf/server/pxf-api/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Does anyone know how to solve it?

**Comment by frankgh** [comment]
Hi @liuyiffan,

Can you share the commit `sha` for PXF? Also, what OS are you using? Any additional information you can share to debug the issue?
Thanks,

**Comment by frankgh** [comment]
Closing for now, feel free to reopen with additional information to debug the issue.
