### ISSUE TITLE
pxf cluster init Segmentation fault

### ISSUE THREAD

**Issue by se7enshidb** [greenplum-db/pxf#637]
[gpadmin@sdw3 ~]$ pxf cluster init
Segmentation fault
[gpadmin@sdw3 ~]$ pxf version
PXF version 5.15.1

how to do fix this problem, anything else do i need to supply. thx

**Comment by bradfordb-vmware** [comment]
What version of PXF are using? Which Linux version are you running GPDB/PXF on? Can you configure your system to generate a core dump on segfaults and share the backtrace from that core dump?

**Comment by frankgh** [comment]
@se7enshidb this issue seems to happen when your `PXF_HOME` and `PXF_CONF` are the same directory. Make sure your `PXF_CONF` lives outside `PXF_HOME`. For example, if `PXF_HOME` is `/usr/local/pxf-gp6/` then `PXF_CONF` has to live outside this directory.

**Comment by se7enshidb** [comment]
i followed you instruction, move pxf out of GP_HOME directory ,then problem is solved @frankgh
