### ISSUE TITLE
Error while parsing headers of CSV files stored in a NFS from external table

### ISSUE THREAD

**Issue by felipemartim** [greenplum-db/pxf#674]
Hi guys,

I stumbled upon a very strange behaviour while trying to query compressed CSV data stored on a Network File System from an external table using profile file:text or file:csv.

The thing is, if I have more files in the directory than the number of segments in my database, it will stop skipping the header of the CSV files, and will eventually try to parse it as if it was a data row.

Ex.: I have 3 segment hosts, with 6 segments on each. The issue happens when I have more than 18 CSV files in my directory.

It looks like each segment only processes the first CSV file correctly. If I change all the columns of the external table to text or varchar, I'm able to see the name of the columns as data in the table.

I've tested with different CSV files, with different sizes, in different greenplum installations (Ubuntu and RedHat), with different number of segments.

I'm using PXF 6.1 with GP6. This behaviour should be relatively easy to reproduce.

**Comment by bradfordb-vmware** [comment]
I suspect that your external table includes the CSV `HEADER` option, e.g.

```sql
CREATE EXTERNAL TABLE github_674 (<column definitions>)
LOCATION ('pxf://<data-dir>?PROFILE=file:csv')
FORMAT 'CSV' (HEADER);
```

PXF currently doesn't look at this option. What you can do is use the PXF option [`SKIP_HEADER_COUNT`](https://gpdb.docs.pivotal.io/pxf/6-1/using/hdfs_text.html#profile_text) which allows you to specify the number of header lines that PXF should skip in the first split of each file before reading the data. The updated table definition would look something like

```sql
CREATE EXTERNAL TABLE github_674 (<column definitions>)
LOCATION ('pxf://<data-dir>?PROFILE=file:csv&SKIP_HEADER_COUNT=1')
FORMAT 'CSV';
```

**Comment by felipemartim** [comment]
Thanks @bradfordb-vmware! 

It didn't even cross my mind checking the HDFS documentation. The fact that it worked when I had only a few files made me think it was a bug.

I'll try this solution tomorrow and close the issue.

**Comment by felipemartim** [comment]
it worked!
