### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [greenplum-db/pxf#676]
Hi Team, 

I am trying to use **pivotaldata/gpdb6-ubuntu18.04-test**, **pivotaldata/ubuntu-gpdb-debian-dev**,  **pivotaldata/gpdb6-ubuntu18.04-build**, **pivotaldata/gpdb6-centos6-build** and **pivotaldata/gpdb6-centos7-build** images on ARM64 architecture but it seems it is not available for arm64.
  
Do you have any plans on releasing arm64 images on Docker hub? 

It will be very helpful if the image is released for the ARM64 platform. If required, I am happy to contribute. But as a start, can you please provide me with the source code available for these packages.

**Comment by ashuka24** [comment]
The images mentioned are now deprecated on Dockerhub and we have no plans of releasing an image for ARM64.
