### ISSUE TITLE
PXF usage with Teradata JDBC FastExport utility

### ISSUE THREAD

**Issue by kostianu** [greenplum-db/pxf#835]
Hi PXF team, 

We are migrating from Teradata database on Greenplum and need to import a lot of data. 
Teradata provides FastExport utility that optimise data upload process. 
One of the prerequisite for its usage is "JDBC FastExport must be used with a PreparedStatement" (https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html#BGBFBBEG). 

Initially, I've tried many ways: named queries, FETCH_SIZE option, etc. Even though PXF logs says that it's wrapping FastExportManager_Connection and in Teradata's session there info "TYPE=FASTEXPORT" it has no effect on performance. Option "SESSIONS" for Teradata JDBC driver also doesn't have effect.  

I've checked org.greenplum.pxf.plugins.jdbc.JdbcBasePlugin.java and org.greenplum.pxf.plugins.jdbc.JdbcAccessor.java and it uses PreparedStatement only in case of writing to external system, but in case of reading from external system it uses simple java.sql.Statement. 

Could you please add new option to jdbc-site.xml(something like usePreparedStatementOnly) and force PXF to use PreparedStatement in case of this option for read queries also, or in case of "TYPE=FASTEXPORT" just swap to using of PreparedStatement implicitly? Or any other solution that is more sufficient for you.

Enabling FastExport in PXF will significantly improve performance of data import from Teradata, that should make Greenplum more attractive for migration.

**Comment by bradfordb-vmware** [comment]
I've opened #842 that adds a configuration property to have PXF use a `PreparedStatenent` when using the JDBC profile for reading. I don't have a Teradata environment to test if this enables FastExport. If your are running open-source PXF compiled from source, you should be able to build from the branch and test.

**Comment by kostianu** [comment]
Thank you @bradfordb-vmware! I'll let you know once it has been tested.

**Comment by kostianu** [comment]
@bradfordb-vmware your changes made PXF work with FastExport. Thank you!

**Comment by bradfordb-vmware** [comment]
> @bradfordb-vmware your changes made PXF work with FastExport. Thank you!

Awesome! If possible, would you mind sharing the configuration changes you had to make to enable this? We'd like to add an example page to the official documentation.

**Comment by kostianu** [comment]
@bradfordb-vmware, sure
1) added Teradata JDBC jar-file into /lib/pxf/lib  folder

2) made new folder in Greenplum: 
`mkdir /var/lib/pxf/servers/teradatajdbc`

3) added jdbc-site.xml including the following properties into **teradatajdbc** folder

```
    <property>
        <name>jdbc.driver</name>
        <value>com.teradata.jdbc.TeraDriver</value>
        <description>Class name of the JDBC driver (e.g. org.postgresql.Driver)</description>
    </property>
    <property>
        <name>jdbc.url</name>
        <value>jdbc:teradata://_host_/database=_database_name_,CHARSET=UTF8,TMODE=ANSI,TYPE=FASTEXPORT,RECONNECT_COUNT=50</value>
        <description>The URL that the JDBC driver can use to connect to the database (e.g. jdbc:postgresql://localhost/postgres)</description>
    </property>
```

5) created external table with the following config

`LOCATION ('pxf://HR.Employees?PROFILE=Jdbc&SERVER=teradatajdbc')
FORMAT 'CUSTOM' (FORMATTER='pxfwritable_import');` 

To check that FastExport works you may add LOG=INFO into jdbc.url property and check log/pxf-app.out - it should contains something similar to:

`FastExport found 2 AMP(s) in anmpc2 and created 2 FastExportConnection(s) and 2 FastExportPreparedStatement(s) with SESSIONS=8`
