### ISSUE TITLE
pxf connect hive occur error

### ISSUE THREAD

**Issue by sydt2014** [greenplum-db/pxf#93]
when greenplum read hive data by pxf it occur:
 hive.metastore - set_ugi() not successful, Likely cause: new client talking to old server. Continuing without it. Other configuration is correct and hive version is 1.2.1 and pxf-hive is compiled by hive-1.2.1. However, it still report version error

**Comment by frankgh** [comment]
@sydt2014 what version of PXF are you using?

**Comment by frankgh** [comment]
Fixed in version 5.1.1
