### ISSUE TITLE
Compression on external writable tables

### ISSUE THREAD

**Issue by vishalrp** [greenplum-db/pxf#939]
Hello, 

Can someone please share an example of how we can enable compression when using pxf to write to Azure Blob Storage? 

For readable data it automatically figures it out. However, for writable external tables I’d like to export data in text+gzip or even orc+zlib compression if possible. 

Thanks!

**Comment by bradfordb-vmware** [comment]
You can enable compression using the `COMPRESSION_CODEC` option in the `CREATE WRITABLE EXTERNAL TABLE LOCATION` clause;

* [About Writing ORC data](https://docs.vmware.com/en/VMware-Tanzu-Greenplum-Platform-Extension-Framework/6.5/tanzu-greenplum-platform-extension-framework/GUID-hdfs_orc.html)
* [Writing Text Data to HDFS](https://docs.vmware.com/en/VMware-Tanzu-Greenplum-Platform-Extension-Framework/6.5/tanzu-greenplum-platform-extension-framework/GUID-hdfs_text.html)

Something like

```sql
CREATE WRITABLE TABLE (...)
LOCATION ('pxf://<path>?PROFILE=wasbs:text&COMPRESSION_CODEC=gzip')
FORMAT 'CUSTOM' (formatter=pxfwritable_export)
```
