### ISSUE TITLE
修改PXF_HOST无效，netstat结果pxf进程仍然是监听0.0.0.0:5888，希望监听具体ip

### ISSUE THREAD

**Issue by linyuanpapapa** [greenplum-db/pxf#974]
https://docs-cn.greenplum.org/v6/pxf/cfghostport.html#proc
根据官方文档在数据库用户的环境变量里增加了PXF_HOST变量
`export PXF_HOST=127.0.0.1`
重启数据库和pxf，重新执行netstat发现PXF进程仍然监听的是0.0.0.0:5888，期望为127.0.0.1:5888
查看/proc/pid/environ，新增的环境变量其实已经被加载，但没有生效

**Comment by linyuanpapapa** [comment]
在conf下的pxf-application.properties新增server.address=127.0.0.1可以达到目的，但不知道会不会对功能有所影响。

**Comment by yimingli-vmware** [comment]
For a future reference, here is the English version of your question:

According to the document [configure pxf service host and port](https://docs.vmware.com/en/VMware-Greenplum-Platform-Extension-Framework/6.6/greenplum-platform-extension-framework/cfghostport.html), you've added `export PXF_HOST=127.0.0.1` to your `.bashrc`. You've restarted GPDB and pxf, but your pxf is still listening on `0.0.0.0:5888` by running `netstat`. What you expected is pxf should now listen on `127.0.0.1:5888`. By looking at `/proc/pid/environ` you found out that environment variable `PXF_HOST` has been loaded, but seems like it didn't take effect.

You also tried to add a new property `server.address=127.0.0.1` in `conf/pxf-application.properties` and this achieved what you want, but you are not sure whether it will affect the overall functionality.

**Comment by yimingli-vmware** [comment]
Hi linuanpapapa,

Let me provide you some context before answering your question. 

`PXF_HOST` and `PXF_PORT` are PXF client setting, for most cases the client is GPDB. These two are used for the communication between PXF and GPDB. When a query comes into GPDB external table with PXF protocol, GPDB will trigger a C file `pxf.so` on its side. `pxf.so` will carry the values set to `PXF_HOST` and `PXF_PORT` to send an HTTP request to a PXF Java server with an URL begin with `http://{PXF_HOST}:{PXF_PORT}`.  `PXF_HOST` should be set to a PXF IP address. It tells your GPDB which pxf it should send requests to. 

`server.address=127.0.0.1` is a Tomcat setting of your local machine.  It tells your local PXF server  to accept requests only from local server (`server.address=127.0.0.1`), or any server (`server.address=0.0.0.0`). But limit your PXF to accept requests only from your localhost will improve the security.

To answer your question, I would say adding PXF_HOST into `.bashrc` and restart PXF and GPDB is the correct way to configure PXF client. And adding `server.address` into the `pxf-application.properties` is also the correct way to configure PXF server. Currently we don't have document about the `server.address`, but we will update our document about configuring this option.

But my question for you is what is your purpose of changing the `PXF_HOST` and `server.address`? Do you want to limit the connections that pxf accept? Let me know if you have more questions.

你好linuanpapapa，

我想先给你提供一些背景知识，希望能帮助你理解你要如何设置`PXF_HOST`和`server.address`这两个变量。

在你引用的Greenplum PXF 配置文档中提到了`PXF_HOST`和`PXF_PORT`，这两个属于PXF的客户端的设置，在这里Greenplum是PXF的客户端。在Greenplum和PXF之间的通信中，需要调用一段GPDB的C代码叫`pxf.so`,  `pxf.so` 会使用`PXF_HOST`和`PXF_PORT`设置的值向PXF server发送一个HTTP请求，HTTP的URL会以`http://{PXF_HOST}:{PXF_PORT}`开头。这里`PXF_HOST`的值应该是一个PXF的IP地址，他会告诉GPDB应该和哪个PXF建立通信连接。

而`server.address`是一个Tomcat对你本机的网络通信设置，不是Greenplum的一个特定的设置。这个设置的值会允许你本地的PXF选择仅接受本机的请求（127.0.0.1），还是任何机器发送的请求（0.0.0.0）。如果限制PXF仅接受本地的请求（127.0.0.1）会提高PXF通讯的安全性。

回到你的问题，按照文档把PXF_HOST写入.bashrc并重启GPDB和PXF是正确的方式去设置PXF客户端；把`server.address`写进`conf/pxf-application.properties`并重启PXF也是正确的方式去设置PXF server。目前我们PXF的文档并没有描述关于`server.address`的设置，不过我们会在后续的文档中加入。

但是我们目前还不太清楚你想设置这两个值的目的是什么？希望之前的描述可以帮助你正确理解并设置这两个值。

**Comment by linyuanpapapa** [comment]
谢谢您的回复！
修改这两个值的目的主要是因为公司对服务器进行了安全扫描，认为pxf服务监听0.0.0.0:5888是不合理、有安全风险的，所以建议整改。

**Comment by yimingli-vmware** [comment]
English version of the reply:
After having a security scan of company's servers, it is risky for pxf to listen on 0.0.0.0:5888, so they try to change `PXF_HOST` and add `server.address`.

Hi @linyuanpapapa,

Our team has decided to update our document to restrict the server address to localhost to improve security ([PR 976](https://github.com/greenplum-db/pxf/pull/976) ). We are still under the discussion about whether to set the default value of server address to localhost, but that will not block you to improve pxf security on your side. Thank you for bringing up this issue.

**Comment by denalex** [comment]
BTW, there is no need to update `PXF_HOST` in this scenario, where PXF JVM is still colocated with the segments.

**Comment by linyuanpapapa** [comment]
> BTW, there is no need to update `PXF_HOST` in this scenario, where PXF JVM is still colocated with the segments.

thanks for the heads-up！
